# Generated by Django 2.2.6 on 2019-12-16 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messages',
            name='chat_session',
        ),
    ]
