# Generated by Django 2.2.6 on 2019-12-16 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_remove_messages_chat_session'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messages',
            name='message_time',
        ),
    ]
