# Generated by Django 2.2.6 on 2019-12-16 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_remove_messages_message_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='message_from',
            field=models.BooleanField(default=0),
        ),
    ]
