# Generated by Django 2.2.8 on 2019-12-18 08:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_auto_20191216_1744'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatroom',
            options={'ordering': ['start_time']},
        ),
        migrations.AddField(
            model_name='chatroom',
            name='active_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='messages',
            name='chat_session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chat.Chatroom'),
        ),
        migrations.AddField(
            model_name='messages',
            name='message_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='Counsellor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
